version: '3.5'
services:

  # NATS JetStream cluster for bot queues
  bots_queues_nats_node_1:
    container_name: bots_queues_nats_node_1
    image: nats:2.6.6
    dns_search: example.net
    entrypoint: /nats-server
    command: --name N1 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://bots_queues_nats_node_1:4245,nats://bots_queues_nats_node_2:4245,nats://bots_queues_nats_node_3:4245 -p 4222
    networks:
    - nats
    ports:
    - 4222:4222
    volumes:
    - ./docker/nats/data/n1:/data

  bots_queues_nats_node_2:
    container_name: bots_queues_nats_node_2
    image: nats:2.6.6
    dns_search: example.net
    entrypoint: /nats-server
    command: --name N2 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://bots_queues_nats_node_1:4245,nats://bots_queues_nats_node_2:4245,nats://bots_queues_nats_node_3:4245 -p 4222
    networks:
    - nats
    ports:
    - 4223:4222
    volumes:
    - ./docker/nats/data/n2:/data

  bots_queues_nats_node_3:
    container_name: bots_queues_nats_node_3
    image: nats:2.6.6
    dns_search: example.net
    entrypoint: /nats-server
    command: --name N3 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://bots_queues_nats_node_1:4245,nats://bots_queues_nats_node_2:4245,nats://bots_queues_nats_node_3:4245 -p 4222
    networks:
    - nats
    ports:
    - 4224:4222
    volumes:
    - ./docker/nats/data/n3:/data

networks:
  nats: {}